version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/generators/llamacpp/resources/'
    schedule:
      interval: 'daily'
      time: '12:00'
    versioning-strategy: increase
    labels:
      - 'theme: dependencies'

  - package-ecosystem: 'maven'
    directory: '/generators/llamacpp/resources/'
    schedule:
      interval: 'daily'
      time: '12:00'
    labels:
      - 'theme: dependencies'
      - 'theme: java'
